services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: ddb-migrations-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
